routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/logout', function () {
	Auth::logout();
    return view('welcome');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('producto', 'ProductoController');
Route::post('producto/listing-datatable', 'ProductoController@datatable');

app/Producto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Producto extends Model
{
    public $table = 'producto';
    
}

app/Http/Controllers/ProductoController.php
<?php

namespace App\Http\Controllers;

use App\Producto;
use Illuminate\Http\Request;
use DataTables;
use Validator;
use Auth;
use File;
use Illuminate\Support\Facades\Storage;
use Carbon\Carbon;
use URL;

class ProductoController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }



    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        //Columnas Datatable JSON - AJAX
        $data['columnas_datatable_json']=array(['data'=>'id','name'=> 'producto.id'],['data'=>'nombre','name'=>'producto.nombre'],['data'=>'descripcion','name'=>'producto.descripcion'],['data'=>'foto','name'=>'foto'],['data'=>'precio','name'=>'precio'],['data'=>'acciones','name'=>'acciones','orderable'=>false,'searchable'=>false]);

        $data['url_datatable_ajax']=url('producto/listing-datatable');

        return view('producto.index')->With($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['tipo_view']='create';

        return view('producto.create')->with($data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validation = Validator::make($request->all(), [
            'nombre' => 'required',
            'descripcion' => 'required',
            'precio' => 'required',
        ]);            

        if($validation->fails()) { return back()->withErrors($validation)->withInput();}

        $id=Auth::user()->id;

        $producto=new Producto();
        $producto->nombre=$request->nombre;
        $producto->descripcion=$request->descripcion;
        $producto->precio=$request->precio;
        $producto->created_by=$id;
        $producto->estado=1;
        $producto->save();

        $url_foto='';
        if($request->file('foto')){        
            $nombre_archivo = $id.'_'.Carbon::now()->format('Y_m_d_h_i_s').'.'.$request->file('foto')->getClientOriginalExtension();
            $url_foto='producto/'.$id.'/'.$nombre_archivo;
            Storage::disk('public')->put('producto/'.$id.'/'.$nombre_archivo, File::get($request->file('foto')), 'public');
        }

        $producto->foto=$url_foto;
        $producto->update();


        $response = [
            'icono' => 'success',
            'titulo' => 'Producto creado con éxito.',
            'mensaje' => 'El registro se guardo satisfactoriamente',
        ];


        return redirect(url('producto'))->with('response', $response);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['producto']=Producto::find($id);
        return view('producto.show')->with($data);
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['tipo_view']='edit';
        $data['producto']=Producto::find($id);

        return view('producto.create')->with($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validation = Validator::make($request->all(), [
            'nombre' => 'required',
            'descripcion' => 'required',
            'precio' => 'required',
        ]);            

        if($validation->fails()) { return back()->withErrors($validation)->withInput();}

        $producto=Producto::find($id);
        $producto->nombre=$request->nombre;
        $producto->descripcion=$request->descripcion;
        $producto->precio=$request->precio;
        $producto->updated_by=Auth::user()->id;
        $producto->estado=1;

        $url_foto='';
        if($request->file('foto')){        
            $nombre_archivo = $id.'_'.Carbon::now()->format('Y_m_d_h_i_s').'.'.$request->file('foto')->getClientOriginalExtension();
            $url_foto='producto/'.$id.'/'.$nombre_archivo;
            Storage::disk('public')->put('producto/'.$id.'/'.$nombre_archivo, File::get($request->file('foto')), 'public');
        }
        $producto->foto=$url_foto;
        $producto->update();

        $response = [
            'icono' => 'success',
            'titulo' => 'Producto actualizado con éxito.',
            'mensaje' => 'El registro se actualizo satisfactoriamente',
        ];


        return redirect('producto')->with('response', $response);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $producto=Producto::find($id);
        $producto->estado=0;
        $producto->update();

        return response()->json(['eliminado'=>true]);
    }
    public function datatable(Request $request){

        $productos=Producto::select(['id','nombre','descripcion','foto','precio'])->where('estado',1);

        return Datatables::of($productos)
        ->editColumn('id', function($producto) {
            $html='<a href="'.url('producto/'.$producto->id.'').'">'.$producto->id.'</a>'; 
          return $html;
        })
        ->editColumn('nombre', function($producto) {
            $html='<a href="'.url('producto/'.$producto->id.'').'">'.$producto->nombre.'</a>'; 
          return $html;
        })
        ->editColumn('acciones', function($producto) {

            $html='<a class="btn btn-success " href="'.url('producto/'.$producto->id.'').'"><i class="fa fa-eye"></i></a>'.
                      '<a class="btn btn-danger"  onclick="eliminar('.$producto->id.')"><i class="fa fa-trash"></i></a>'.
                      '<a class="btn btn-primary" href="'.url('producto/'.$producto->id.'/edit').'"><i class="fa fa-edit"></i></a>';
          return $html;
        })
        ->editColumn('foto', function($producto) {
           $html=""; 
           if($producto->foto)
           {
                 $html.='<img src="'.asset('storage/'.$producto->foto).'" width="100px" height="100px"></img>';
           }
           else
           {
                $html='<span class="badge badge-danger">No Registra</span>';
           }
           return $html."";
        })
        ->rawColumns(['id','acciones','nombre','foto'])  //Sirve para imprimir Columnas Crudas (Columna que contienen HTML)
        ->make(true);
    
    }
}

resources/views/producto/create.blade.php
@extends('layouts.app')

@section('css_level')
		<!-- FileInput -->
	<link href="{{mix('/css/fileinput.css')}}" rel="stylesheet" />
@endsection


@section('content')
<div class="container">
    <div class="row justify-content-center">


		<div class="col-md-12 bg-light rounded-lg" >
				@if($tipo_view=='edit')
					<form action="{{url('producto/'.$producto->id)}}" id="form-producto" method="POST" id="form-global" files="true" enctype="multipart/form-data" >
	        		<input type="hidden" name="_method" value="PUT" id="_method"> 
				@else
					<form action="{{route('producto.store')}}" id="form-producto" method="POST" id="form-global" files="true" enctype="multipart/form-data" >
				@endif
	        	<input type="hidden" name="_token" value="{{ csrf_token() }}" id="token"> 
				<hr>
				<div class="row">	

			 		<div class="form-group col-md-6">
						<label for="nombre">Nombre <span style="color:red">(*)</span></label>
						<input type="text" class="form-control" value='{{(isset($producto)?$producto->nombre:"")}}' id="nombre" name="nombre" required>
					</div>
			 		<div class="form-group col-md-6">
						<label for="precio">Precio <span style="color:red">(*)</span></label>
						<input type="text" class="form-control" value='{{(isset($producto)?$producto->precio:"")}}' id="precio" name="precio" required>
					</div>
					<div class="form-group col-md-12">
						<label for="descripcion">Descripción <span style="color:red">(*)</span></label>
						<textarea class="form-control" value='{{(isset($producto)?$producto->descripcion:"")}}' id="descripcion" name="descripcion" required rows="3">{{(isset($producto)?$producto->descripcion:"")}}</textarea>
					</div>
					<div class="form-group col-md-6">
						@if(isset($producto))
							@if($producto->foto)
								<img src="{{ asset('storage/'.$producto->foto)}}" width="150px" height="150px"><br>
							@endif
						@endif
						<label for="foto">Foto </label>
						<input type="file" accept=".png, .jpeg, .jpg, .gif" class="form-control input_adjundtar_archivo"  id="foto" name="foto" ></input>
					</div>

	 			</div>
				<div class="form-group">
					<a class="btn btn-warning" href="{{ url()->previous() }}" ><i class="fa fa-reply-all"></i> Regresar</a>	
					<button type="submit" class="btn btn-success"><i class="fa fa-save"></i> Guardar</button>
					<button type="reset" class="btn btn-danger"><i class="fa fa-times-circle"></i> Cancelar</button>
				</div>
				<br>
			</form>
		</div>


    </div>
</div>
@endsection


<!-- Css -->
@section('js_level')
	<!-- Plugin Fileinput -->
	<script src="{{mix('/js/fileinput.js')}}"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.1/dist/jquery.validate.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.1/dist/additional-methods.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.1/dist/localization/messages_es.min.js"></script>
	<!-- FileInput -->
	<link href="{{mix('/css/fileinput.css')}}" rel="stylesheet" />
	<script type="text/javascript">

		//Validation Jquery
	    $('#form-producto').validate();


	    // Plugin para Input's archivos
	    $('.input_adjundtar_archivo').fileinput({
	        theme: 'fa',
	        language: 'es',
	        allowedFileExtensions: ['jpg', 'png', 'gif'],
	        showUpload: false,
	        showCaption: false,  
	        showUploadedThumbs: false, 
	        showRemove: true,
	        dropZoneEnabled: false,
	        maxFileCount: 10,
	        mainClass: "input-group-lg"
	    });

		@if(session('response'))
			 Swal.fire(
				  '{{ session("response")["titulo"] }}',
				  '{{ session("response")["mensaje"]}}',
				  '{{ session("response")["icono"]}}'
				);
		  {{session()->forget('response')}}
		@endif
	</script>

@endsection

resources/views/producto/index.blade.php
@extends('layouts.app')
<!-- Css -->
@section('css_level')
	<!-- Datatable -->
    <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet"></link>
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">

		<div class="col-md-12 bg-light rounded-lg">
      		<br>
			<h2 style="font-weight: bold;" class="text-info"><i class="fa fa-bars" aria-hidden="true"></i>&nbsp;Listado de Productos</h2>
			<hr>
	      	<div class="text-right">
				<a class="btn btn-primary" href="{{route('producto.create')}}"  style="font-weight: bold;">Crear Producto</a>
			</div>
          	<br>
	        <div class="card border-success mb-3">
	              <div class="card-header text-white bg-success"><h4 style="font-weight: bold;"><i class="fa fa-bars" aria-hidden="true"></i> Listado de Productos<h4></div>
	              <div class="card-body">
	                	<div class="col-md-12">                    		
    						<table class="table table-striped no-footer"  style="width:100%" id="datatable">
    							<thead>
    								<tr>
    									<th>Id</th>
    									<th>Nombre</th>
    									<th>Descripción</th>
    									<th>Foto</th>
    									<th>Precio</th>
    									<th>Acciones</th>
    								</tr>					
    							</thead>
    							<tbody>
    							</tbody>
    						</table>
	                	</div>
	              </div>
	          </div>
	      	<br>
		</div>


    </div>
</div>
@endsection


<!-- Css -->
@section('js_level')

	<!-- Datatable Script's-->
	<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
	<!-- Include donde se encuentra la inicializacion del datatable -->

	<script type="text/javascript">

	 let language =
	  {
	    'sProcessing': 'Procesando...',
	    'sLengthMenu': 'Mostrar _MENU_ registros',
	    'sZeroRecords': 'No se encontraron resultados',
	    'sEmptyTable': 'Ningún dato disponible en esta tabla',
	    'sInfo': 'Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros',
	    'sInfoEmpty': 'Mostrando registros del 0 al 0 de un total de 0 registros',
	    'sInfoFiltered': '(filtrado de un total de _MAX_ registros)',
	    'sInfoPostFix': '',
	    'sSearch': 'Buscar:',
	    'sUrl': '',
	    'sInfoThousands': ',',
	    'sLoadingRecords': 'Cargando...',
	    'oPaginate': {
	        'sFirst': 'Primero',
	        'sLast': 'Último',
	        'sNext': 'Siguiente',
	        'sPrevious': 'Anterior'
	    },
	    'oAria': {
	        'sSortAscending': ': Activar para ordenar la columna de manera ascendente',
	        'sSortDescending': ': Activar para ordenar la columna de manera descendente'
	    }
	  };

	  function renderizar_datatable(id_datatable,columns,url_ajax)
	  {

	      var token = '{{ csrf_token() }}';
	      var datatable = $(id_datatable).DataTable({
	        processing: true,
	        serverSide: true,
	        search: true,
	        ordering: true,
	        scrollX:true,
	        searchable:true,
	        searching: true,
	        language: language,
	        ajax: {
	          url: url_ajax,
	          headers: {'X-CSRF-TOKEN': token},
	          method: 'POST',
	          data: (d) => {
	            if(typeof dataFilterDatatable === 'function') {
	              let data_filter = dataFilterDatatable();
	              for (var item in data_filter) {
	                d[item] = data_filter[item]
	              }
	            }
	          }
	        },
	        columns: columns,
	        autoWidth: true,
	      });

	      return datatable;
	  }


	  function eliminar(id)
	  {   

  		Swal.fire({
	        title: 'Estas seguro de eliminar este Producto?',
	        text: "La información de este Producto se borrara",
	        icon: 'warning',
	        showCancelButton: true,
	        confirmButtonText: 'Si',
	        cancelButtonText: 'No',
	        reverseButtons: true
	      }).then((result) => {
	        if(result) 
	        { 
	           $.ajax({
	              url: "{{ url('producto') }}/" + id,
	              method: 'DELETE',
	              headers: {'X-CSRF-TOKEN': '{{csrf_token()}}'},
	              success: function(result){  
	                  Swal.fire('Producto Eliminado','Se elimino la información de este Producto ','success');
	                  window.location.href='{{url("producto")}}';
	              },
	              error: function (data) {
	                  Swal.fire('Producto No Eliminado','El propietario no pudo ser Eliminado','error');
	              }
	          });

	        } 
	      });

	  }

	$(document).ready(function(){
		var columns=JSON.parse('{!! json_encode($columnas_datatable_json) !!}');
		var url_datatable_ajax='{{$url_datatable_ajax}}';
		var datatable=renderizar_datatable('#datatable',columns,url_datatable_ajax);
	});

	@if(session('response'))
		 Swal.fire(
			  '{{ session("response")["titulo"] }}',
			  '{{ session("response")["mensaje"]}}',
			  '{{ session("response")["icono"]}}'
			);
	  {{session()->forget('response')}}
	@endif
	</script>

@endsection

resources/views/producto/show.blade.php
@extends('layouts.app')


@section('content')
<div class="container">
    <div class="row justify-content-center">

		<div class="col-md-12 bg-light rounded-lg" >
				<hr>
				<div class="row">		

			 		<div class="form-group col-md-6">
						<h4>Nombre:</h4>
						<span>{{(isset($producto)?$producto->nombre:"No Registra")}}</span>
					</div>
			 		<div class="form-group col-md-6">
						<h4>Precio:</h4>
						<span>{{(isset($producto)?$producto->precio:"No Registra")}}</span>
					</div>
					<div class="form-group col-md-6">
						<h4>Descripción:</h4>
						<span>{{(isset($producto)?$producto->precio:"No Registra")}}</span>
					</div>
					<div class="form-group col-md-6">
						<h4>Foto:</h4>
						@if(isset($producto))
							@if($producto->foto)
								<img src="{{ asset('storage/'.$producto->foto)}}" width="150px" height="150px"><br>
							@else
								<span>{{(isset($producto)?$producto->precio:"No Registra")}}</span>
							@endif
						@endif
					</div>

	 			</div>
				<div class="form-group">
					<a class="btn btn-warning" href="{{ url()->previous() }}" ><i class="fa fa-reply-all"></i> Regresar</a>	
                    <a class="btn btn-danger"  onclick="eliminar({{$producto->id}})"><i class="fa fa-trash"></i> Eliminar</a>
                    <a class="btn btn-primary" href="{{url('producto/'.$producto->id.'/edit')}}"><i class="fa fa-edit"></i> Editar</a>
				</div>
				<br>
			</form>
		</div>
    </div>
</div>
@endsection


<!-- Css -->
@section('js_level')
	<script type="text/javascript">
		@if(session('response'))
			 Swal.fire(
				  '{{ session("response")["titulo"] }}',
				  '{{ session("response")["mensaje"]}}',
				  '{{ session("response")["icono"]}}'
				);
		  {{session()->forget('response')}}
		@endif
	</script>

@endsection